version: "3.8"

services:
    api:
        #image: node:16-alpine
        image: api:latest
        ports:
            - 3001:3000
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: calories
    
    ui: 
        image: ui:latest
        ports:
            - 3000:3000


    mysql:
        image: mysql:latest
        volumes:
            - calories-sql-data:/var/lib/mysql
            - ./src/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: calories
        ports:
            - 3307:3306
        
volumes:
  calories-sql-data:
