version: "3.8"

services:
    app:
        image: node:16-alpine
        command: sh -c "npm install && npx wait-on tcp:mysql:3306 && npm run start"
        ports:
            - 3001:3000
        working_dir: /app
        volumes:
            - ./:/app
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: calories
    
    mysql:
        image: mysql:latest
        volumes:
            - munchy-sql-data:/var/lib/mysql
            - ./src/sql:/docker-entrypoint-initdb.d
        environment:  
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: calories
        ports:
            - 3307:3307
        
volumes:
  munchy-sql-data:
