version: "3.8"

services:
    api:
        #image: node:16-alpine
        image: api:latest
        command: sh -c "npm install && npx wait-on tcp:mysql:3306 && npm run start"
        ports:
            - 3001:3000
        working_dir: /app
        volumes:
            - ./:/app
        environment:
            MYSQL_HOST: mysql
            MYSQL_USER: root
            MYSQL_PASSWORD: secret
            MYSQL_DB: calories
    
    ui: 
        image: ui:latest
        #image: node:16-alpine
        command: sh -c "npm install && npm start --port 8000"
        ports:
            - 8000:8000
        working_dir: /app
        volumes:
            - ./:/app


    mysql:
        image: mysql:latest
        volumes:
            - calories-sql-data:/var/lib/mysql
            - ./src/sql:/docker-entrypoint-initdb.d
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: calories
        ports:
            - 3307:3307
        
volumes:
  calories-sql-data:
